<?php


Route::group(["prefix" => "admin", "middleware" => ["web"]], function () {
    
    // Core/uneditable routes (not copied over on publish)
    Route::group(["namespace" => "Thinmartiancms\Cms\App\Http\Controllers\Core"], function() {
        Route::auth();
    });
    
    // Custom/editable routes (copied over on publish)
    Route::group(["namespace" => "Thinmartiancms\Cms\App\Http\Controllers\Custom", "middleware" => ["auth.cms"]], function() {
        
        Route::get("/", ["uses" => "DashboardController@index", "as" => "cms-dashboard"]);
        
        /* START: routes to be generated by YAML */
        Route::resource("users", "UsersController", ["except" => "show"]);
        /* END: routes to be generated by YAML */
        
    });
    
});